/**
5. Write a program that create List of Id with 10 items and use 2 different 
loop (for loop and for each loop )to print out all value for practice 
    - continue from above
     if the any ID match exactly '001xxxxxxxxxxxxxxx' 
     then break out of the loop
 */

List <ID> listId = new List <Id> {'01DDn00000DG0by', '00DDn00000DG0by', '02DDn00000DG0by',
'00DDn00000DG0by', '00DDn00000DG0by', '00DDn00000DG0by', '00DDn00000DG0by'} ;

for(Integer index=0; index<10 ;index++) {
    
}

