// Task 7

/*checks if the first number is greater than the second number and the second number is greater than the third number. 
If this is true, the program should print "The first number is the largest." 
If not, the program should print "The first number is not the largest."*/


Integer num1 = 100;
Integer num2 = 20;
Integer num3 = 30;

if(num1 > num2 && num1 > num3){
   System.debug('Thae first number is the largest');
}else{
   System.debug('The first number is not the largest');
}

