/**
3. Declare and initialize a String variable with one character
check the if character is vowel 'a' , 'e', 'o' , 'u' , 'i'
if true print it's a vowel 
else print it's not a vowel!
 */

 String character = 'a' ;

 if(character == 'a' || character == 'e' || character == 'o' || character == 'u' || character == 'i') {
    System.debug('It\' a vowel'); 
 }else{
    System.debug('It is not a vowel'); 
 }

 